# Generated by Django 4.2.5 on 2023-09-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_remove_room_pet_friendly_alter_amenity_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pet_friendly',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='room',
            name='city',
            field=models.CharField(default='LA', max_length=80),
        ),
        migrations.AlterField(
            model_name='room',
            name='country',
            field=models.CharField(default='US', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='kind',
            field=models.CharField(choices=[('entire_place', 'Entire Place'), ('private_room', 'Private Room'), ('shared_room', 'Shared Room')], max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default='dd', max_length=180),
        ),
    ]
