databases:
  - name: airbnb
    databaseName: airbnb
    user: mysite

services:
  - type: web
    name: airbnb
    runtime: python
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: airbnb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
