# Generated by Django 4.2.5 on 2023-09-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_booking_alter_review_payload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='booking',
        ),
        migrations.AlterField(
            model_name='review',
            name='payload',
            field=models.TextField(),
        ),
    ]
