# Generated by Django 4.2.5 on 2023-09-26 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_host_approval_state_booking_is_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='host_approval_state',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_cancelled',
        ),
    ]
